create table INTERFACE_MASTER (
INTERFACE_ID	NUMBER(5,0) not null,
INTERFACE_TYPE	VARCHAR2(30 ) not null,
INTERFACE_NAME	VARCHAR2(240 ) not null,
INTERFACE_DESCRIPTION	VARCHAR2(500 ),
INPUTFILE_NAME_FORMAT	VARCHAR2(240 ),
OUTPUTFILE_NAME_FORMAT	VARCHAR2(240 ),
INPUTFILE_VERSION_NUMBER	NUMBER(10,0),
OUTPUTFILE_VERSION_NUMBER	NUMBER(10,0),
MIN_VERSION_NUMBER	NUMBER(10,0),
MAX_VERSION_NUMBER	NUMBER(10,0),
HEADER_VALIDATION_FLAG	CHAR(1 ),
TRAILER_VALIDATION_FLAG	CHAR(1 )
);

create table INTERFACE_CONFIGURATION (
FIELD_ID	NUMBER(5,0)  not null,
INTERFACE_ID	NUMBER(5,0) not null,
FIELD_NAME	VARCHAR2(240 ) not null,
FIELD_DESCRIPTION	VARCHAR2(240 ),
FIELD_TYPE	CHAR(1 ) not null,
SOURCE	VARCHAR2(120 ),
SOURCE_COLUMN	VARCHAR2(120 ),
TARGET	VARCHAR2(120 ),
TARGET_COLUMN	VARCHAR2(120 ),
TRUNCATE_FLAG	CHAR(1 ) not null,
DATA_FORMATTING_STRING	VARCHAR2(1000 ) ,
JAVA_FORMATTING_STRING	VARCHAR2(1000 ),
INPUT_FIELD_LENGTH	NUMBER(5,0),
OUTPUT_FIELD_LENGTH	NUMBER(5,0),
RECORD_LEVEL	NUMBER(5,0),
INPUT_POSITION	NUMBER(5,0),
OUTPUT_POSITION	NUMBER(5,0),
ALIGNMENT_IND	CHAR(1 )
);

