package org.abc.framework.bean.common;

public interface Constants
{
	String FILLER="FILLER";
	String UNDER_SCORE="_";
	String NEW_LINE="\n";
	String BLANK_SPACE="";
	String HEADER_FOOTER_TOTAL_COUNT_WITH_HEADER_FOOTER="TOTAL_COUNT_WITH_HEADER_FOOTER";
	String HEADER_FOOTER_TOTAL_COUNT="TOTAL_COUNT";
	String HEADER_FOOTER_TOTAL_COUNT_WITH_HEADER="TOTAL_COUNT_WITH_HEADER";
	String LINE_TAB_BREAK = "\n\t";
	String LEVEL = "LEVEL";
	String HEADER_RECORD_LEVEL="0";
	String TRAILER_RECORD_LEVEL="-1";
	String RECORD_COUNT_WITH_HEADER_FOOTER = "RECORD_COUNT_WITH_HEADER_FOOTER";
	String RECORD_COUNT = "RECORD_COUNT";
	String HASH_COUNT = "HASH_COUNT";
	String FIELD_TYPE_DETAIL_RECORD = "D";
	String FIELD_TYPE_HEADER_RECORD = "H";
	Object FIELD_TYPE_TRAILER_RECORD = "T";
	
	
}
