insert into INTERFACE_MASTER(INTERFACE_ID,INTERFACE_NAME,INTERFACE_TYPE,INTERFACE_DESCRIPTION,INPUTFILE_NAME_FORMAT,OUTPUTFILE_NAME_FORMAT,INPUTFILE_VERSION_NUMBER,OUTPUTFILE_VERSION_NUMBER,MIN_VERSION_NUMBER,MAX_VERSION_NUMBER,HEADER_VALIDATION_FLAG,TRAILER_VALIDATION_FLAG) values (1,'MERCH_CLASS','DB_TO_FILE','','','abc','1','1','1','100','N','N');

insert into INTERFACE_CONFIGURATION (FIELD_ID,INTERFACE_id,FIELD_NAME,FIELD_DESCRIPTION,SOURCE_COLUMN,SOURCE,target_column, target,truncate_flag, field_type,Data_FORMATTING_STRING,JAVA_FORMATTING_STRING,input_FIELD_LENGTH,output_FIELD_LENGTH,RECORD_LEVEL,input_POSITION,output_position,ALIGNMENT_IND) values('1','1','ID','ID','ID','VENDOR_STAGE','','','','N','','','6','6','1','1','1','L');

insert into INTERFACE_MASTER(INTERFACE_ID,INTERFACE_NAME,INTERFACE_TYPE,INTERFACE_DESCRIPTION,INPUTFILE_NAME_FORMAT,OUTPUTFILE_NAME_FORMAT,INPUTFILE_VERSION_NUMBER,OUTPUTFILE_VERSION_NUMBER,MIN_VERSION_NUMBER,MAX_VERSION_NUMBER,HEADER_VALIDATION_FLAG,TRAILER_VALIDATION_FLAG) values (2,'DYNAMIC_READER_TEST','DB_TO_FILE','','','abc','1','1','1','100','N','N');

insert into INTERFACE_CONFIGURATION (FIELD_ID,INTERFACE_id,FIELD_NAME,FIELD_DESCRIPTION,SOURCE_COLUMN,SOURCE,target_column, target,truncate_flag, field_type,Data_FORMATTING_STRING,JAVA_FORMATTING_STRING,input_FIELD_LENGTH,output_FIELD_LENGTH,RECORD_LEVEL,input_POSITION,output_position,ALIGNMENT_IND) values('2','2','NAME','NAME','NAME','DUMMY_STAGE','','','','N','','','28','10','1','2','1','L');

